import { createClient } from "@supabase/supabase-js";
import * as fs from "fs";

const envRaw = fs.readFileSync(".env.local", "utf-8");
for (const line of envRaw.split("\n")) {
  const t = line.trim();
  if (!t || t.startsWith("#")) continue;
  const idx = t.indexOf("=");
  if (idx === -1) continue;
  const key = t.slice(0, idx).trim();
  const val = t.slice(idx + 1).trim().replace(/^["']|["']$/g, "");
  if (!process.env[key]) process.env[key] = val;
}

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const ANTERRAZO_CATEGORY = 99;

interface Fix {
  name: string;
  category_id?: number;
}

const FIXES: Record<number, Fix> = {
   // user-specified
   1280: { name: "Jalón en polea con agarre cerrado" },
   1465: { name: "Curl Araña" },
   1666: { name: "Curl de bíceps con elevación frontal (Involucra hombros)" },
   1209: { name: "Flexiones o plancha en tres apoyos" },
   1468: { name: "Extensión de tríceps tumbado en el suelo (Rompecráneos)" },
   1260: { name: "Curl Martillo con TRX" },

   // approved proposals (brazos/antebrazos)
   1530: { name: "Curl Acostado con Mancuernas" },
   1480: { name: "Extensiones de Tríceps Acostado" },
   1192: { name: "Curl de Bíceps Alternado con Mancuernas" },
   1333: { name: "Curl de Antebrazos (Agarre Supino)", category_id: ANTERRAZO_CATEGORY },
   1483: { name: "Curl Trifecta" },
   1498: { name: "Press en Banco con Mancuernas (Codos Pegados)" },
   1217: { name: "Flexiones de Dedos" },
   1738: { name: "Jalón Ups Agarre Neutro o Remo en TRX" },
   1218: { name: "Flexiones de Rodillas" },
   1462: { name: "Golpes directos" },
   1205: { name: "Curl de Muñeca con Mancuernas", category_id: ANTERRAZO_CATEGORY },
   1771: { name: "Curl de Muñeca en Polea", category_id: ANTERRAZO_CATEGORY },
   1261: { name: "Curl Bíceps Gorila en TRX" },
   1824: { name: "Tate Press con Mancuerna" },

   // ---- ESPALDA (wgerCategoryId=12) ----
   81:   { name: "Remo con Mancuernas" },
   258:  { name: "Jalón al Pecho con Agarre Ancho" },
   259:  { name: "Jalón al Pecho con Agarre Angosto" },
   292:  { name: "Puente de Glúteos", category_id: 9 },
   301:  { name: "Extensiones lumbares de espalda" },
   310:  { name: "Remo Inclinado con Mancuernas" },
   355:  { name: "Jalón Dorsal Recto" },
   380:  { name: "Remo Isométrico en Máquina" },
   395:  { name: "Remo en Polea con Agarre Angosto" },
   448:  { name: "Remos con barra desde el suelo (Pendelay)" },
   510:  { name: "Remo Acostado en Banco" },
   684:  { name: "Jalón Dorsal con Agarre Supino" },
   695:  { name: "Jalón al pecho agarre cerrado (Agarre V)" },
   723:  { name: "Jalón con Agarre Ancho" },
   1124: { name: "Jalón Abierto" },
   1136: { name: "Jalón de Pecho Neutro" },
   1282: { name: "Dominada Isométrica Agarre Supino" },
   1455: { name: "Remo Superman con Toalla" },
   1514: { name: "Caminata Lateral", category_id: 15 },
   1635: { name: "Jalón Modificado" },
   1967: { name: "Remo Sentado" },

   // ---- HOMBROS (wgerCategoryId=13) ----
   79:   { name: "Elevación Frontal Inclinada con Mancuernas" },
   142:  { name: "Rotación Externa en Polea" },
   222:  { name: "Face Pull (Jalón a la Cara)" },
   289:  { name: "Jalón Alto" },
   349:  { name: "Elevación Lateral en Polea a un Brazo" },
   351:  { name: "Elevación Lateral-Frontal" },
   487:  { name: "Elevación de Deltoides Posterior" },
   543:  { name: "Press de Hombro en Máquina" },
   566:  { name: "Press de Hombro con Barra" },
   567:  { name: "Press Militar con Mancuernas" },
   569:  { name: "Press de Hombro en Multipress" },
   570:  { name: "Encogimientos de Hombros" },
   571:  { name: "Encogimientos con Barra" },
   572:  { name: "Encogimientos con Mancuernas" },
   1227: { name: "Remo de Deltoides Posterior con Mancuernas" },
   1378: { name: "Elevación Lateral en Polea (Unilateral)" },
   1441: { name: "Press Overhead Inclinado con Mancuernas" },
   1442: { name: "Press Kreis con Mancuernas" },
   1504: { name: "Bradford Press con Mancuernas" },
   1679: { name: "Ángeles en la Pared" },
   256:  { name: "Elevaciones Frontales" },
   282:  { name: "Flexión en Handstand" },
   346:  { name: "Landmine Press" },
   348:  { name: "Elevación Lateral con Mancuernas" },
   418:  { name: "Press Militar" },
   478:  { name: "Press de Hombro con Mancuernas" },
   578:  { name: "Rotación Externa Acostado de Lado" },
   691:  { name: "Remo Vertical en Multipress" },
   693:  { name: "Remo al Mentón" },
   711:  { name: "Flexión de Pino Contra la Pared" },
   915:  { name: "Vuelo Lateral" },
   916:  { name: "Press en Smith" },
   917:  { name: "Elevación Frontal con Polea" },
   1081: { name: "Dislocates de Hombros" },
   1429: { name: "Rotaciones de Hombro con Mancuerna" },
   1439: { name: "Press Militar desde los Pines" },
   1445: { name: "Envión Olímpico" },
   1446: { name: "Cargada y Envión Olímpico" },
   1536: { name: "Estiramiento de Deltoides" },
   1580: { name: "Remo en Landmine Unilateral" },
   1581: { name: "Trap Press" },
   1582: { name: "Rotación Interna Acostado de Lado" },
   1602: { name: "Scaption con Mancuernas" },
   1710: { name: "Estiramiento Butcher's Block" },
   1711: { name: "Estiramiento Sleeper" },
   1712: { name: "Estiramiento de Flexión Horizontal de Hombros" },
   1714: { name: "Péndulo con Mancuerna (Ejercicio de Codman)" },
   1728: { name: "Rotación Interna de Hombros (Polea)" },
   1729: { name: "Rotación Externa de Hombros (Polea)" },
   1744: { name: "Elevación Lateral en Máquina" },
   1745: { name: "Elevación Frontal en Polea con Barra" },
   1752: { name: "Elevación Lateral-Frontal (Polea)" },
   1753: { name: "Elevación Lateral-Trasera (Polea)" },
   1754: { name: "Elevación Lateral a 45°" },
   1755: { name: "Elevación en Y con Polea" },
   1775: { name: "Aperturas de Deltoides Posterior en Pec Deck" },
   1795: { name: "Jalón Descendente Cruzado Unilateral en Polea" },
   1826: { name: "Jalón-apart con Rotación Externa (Banda)" },
   1835: { name: "Estiramiento de Rotación Externa" },
   1838: { name: "Drills de Hombro con Banda" },
   1841: { name: "Estiramiento de Extensión de Hombros Sentado" },
   1879: { name: "Elevación en Y Inclinado con Mancuernas" },
   1882: { name: "Elevación Lateral en Polea Alta" },
   1893: { name: "Press Overhead con Barra" },
   1914: { name: "Isometría en Paralelas" },
   1920: { name: "Estiramiento Extremo de Hombros" },
   1936: { name: "Aperturas de Deltoides Posterior en Polea (Unilateral)" },
   1968: { name: "Press de Hombro Unilateral con Mancuernas" },

   // ---- BRAZOS (wgerCategoryId=8) ----
   48:   { name: "Curl Inverso de Muñeca con Barra", category_id: 99 },
   91:   { name: "Curl con Barra" },
   92:   { name: "Curl de Bíceps con Mancuerna" },
   202:  { name: "Curl Concentrado con Mancuerna" },
   208:  { name: "Curl en Banco Scott con Mancuernas" },
   275:  { name: "Curl Martillo Concentrado en Polea" },
   465:  { name: "Curl Predicador" },
   493:  { name: "Curl Inverso con Barra" },
   495:  { name: "Curl Inverso" },
   501:  { name: "Ring Dips" },
   549:  { name: "Press de Tríceps Sentado" },
   584:  { name: "Curl Predicador Unilateral" },
   598:  { name: "Press en Smith con Agarre Cerrado" },
   621:  { name: "Curl de Bíceps de Pie" },
   623:  { name: "Curl de Antebrazos de Pie con Cuerda", category_id: 99 },
   655:  { name: "Patada de Tríceps con Mancuernas" },
   660:  { name: "Extensión de Tríceps en Polea con Barra" },
   661:  { name: "Extensión de Tríceps en Máquina" },
   911:  { name: "Skull Crusher Inclinado" },
   913:  { name: "Curl Predicador Inverso" },
   974:  { name: "Curl con Pesa Rusa a Dos Manos" },
   975:  { name: "Curl de Bíceps con Pesa Rusa a una Mano" },
   1185: { name: "Extensión de Tríceps en Polea con Cuerda" },
   1219: { name: "Remo Australiano (Jalón-ups Invertidos)" },
   1224: { name: "Drag Curl con Mancuernas" },
   1225: { name: "Curl de Bíceps Ancho con Mancuernas" },
   1226: { name: "Curl Press de Bíceps con Mancuernas" },
   1273: { name: "Pullover", category_id: 12 },
   1290: { name: "Curl con Agarre Inverso con Barra" },
   1302: { name: "JM Press" },
   1336: { name: "Extensión de Tríceps Overhead con Mancuernas" },
   1372: { name: "Fondos de Tríceps Asistidos" },
   1463: { name: "Peso Muerto con Mancuernas (Agarre Supino)", category_id: 9 },
   1482: { name: "Cheat Curl con Mancuernas" },
   1490: { name: "Patada de Tríceps Acostado" },
   1502: { name: "Curl Martillo Cruzado con Mancuernas" },
   1513: { name: "Extensión de Tríceps Overhead en Polea" },
   1519: { name: "Extensión de Tríceps Overhead" },
   1531: { name: "Curl en Polea" },
   1567: { name: "Curl Martillo Alterno con Mancuernas" },
   1608: { name: "Curl de Bíceps con Peso Corporal" },
   1658: { name: "Curl Predicador con Rotación Externa" },
   1661: { name: "Press de Tríceps en Polea" },
   1662: { name: "Extensión de Tríceps en Polea con Rotación Interna" },
   1668: { name: "Extensión de Tríceps Overhead a un Brazo en Polea" },
   1717: { name: "Extensión de Codo en Polea Alta Unilateral" },
   1881: { name: "Extensión de Muñeca con Mancuernas" },
   1900: { name: "Empuje de Tríceps con Cuerda" },
   1931: { name: "Curl con Mancuernas" },
   1969: { name: "Empuje en Polea Unilateral" },

   // ---- PIERNAS/GLÚTEOS (wgerCategoryId=9) ----
   71:   { name: "Extensión de Cuádriceps a una Pierna" },
   203:  { name: "Sentadilla con Disco" },
   265:  { name: "Puente de Glúteos" },
   268:  { name: "Buenos Días (Good Mornings)" },
   341:  { name: "Sentadillas en Multipress" },
   371:  { name: "Prensa de Piernas" },
   614:  { name: "Saltos de Sentadilla" },
   616:  { name: "Empuje de Sentadilla" },
   627:  { name: "Peso Muerto Piernas Rígidas" },
   630:  { name: "Peso Muerto Sumo" },
   632:  { name: "Sentadilla Sumo" },
   718:  { name: "Sentadilla contra Pared" },
   722:  { name: "Subidas al Cajón con Peso" },
   851:  { name: "Extensión de Cuádriceps" },
   901:  { name: "Hip Thrust con Barra" },
   981:  { name: "Subida a Cajón" },
   986:  { name: "Sentadilla Lateral Izquierda" },
   987:  { name: "Sentadilla Lateral Derecha" },
   988:  { name: "Sentadilla Búlgara Izquierda" },
   989:  { name: "Sentadilla Búlgara Derecha" },
   991:  { name: "Media Sentadilla Izquierda" },
   992:  { name: "Media Sentadilla Derecha" },
   999:  { name: "Zancadas Inversas" },
   1020: { name: "Pistol Squat Derecha" },
   1088: { name: "Peso Muerto Sumo con Mancuernas" },
   1096: { name: "Abducción de Pie" },
   1102: { name: "Zancadas Alternas Hacia Atrás" },
   1116: { name: "Caminata del Granjero con Mancuernas" },
   1131: { name: "Extensión de Glúteos en Polea" },
   1132: { name: "Extensión de Glúteo en Máquina" },
   1195: { name: "Deslizamientos Laterales + Sentadillas" },
   1201: { name: "Sentadilla Dragón" },
   1202: { name: "Abducción de Cadera Acostado de Lado" },
   1208: { name: "Sentadilla Prisionero" },
   1234: { name: "Hip Thrust Unilateral" },
   1243: { name: "Elevación de Pantorrilla Bilateral", category_id: 14 },
   1312: { name: "Sentadilla a Peso Corporal" },
   1324: { name: "Zancada a Peso Corporal" },
   1325: { name: "Press Off Lateral" },
   1361: { name: "Sentadilla Frontal Bilateral con Pesa Rusa" },
   1366: { name: "Sentadilla Dividida con Mancuernas" },
   1370: { name: "Peso Muerto con Mancuernas" },
   1387: { name: "Patadas Isquiotibiales" },
   1388: { name: "Peso Muerto Rumano Unilateral" },
   1391: { name: "Caminata de Elefante" },
   1407: { name: "Sentadilla Cosaca" },
   1408: { name: "Sentadilla contra Pared" },
   1437: { name: "Sentadilla con Pin" },
   1464: { name: "Sentadilla Hack con Pausa" },
   1466: { name: "Elevación de Pantorrilla en Máquina Hack" },
   1503: { name: "Press Rana con Mancuernas" },
   1515: { name: "Press de Punta en Prensa" },
   1521: { name: "Hack Pendular" },
   1527: { name: "Sentadilla Péndulo" },
   1528: { name: "Empuje de Glúteos" },
   1578: { name: "Bisagra de Cadera" },
   1593: { name: "Sentadilla Dividida en Smith" },
   1604: { name: "Zancada Lateral Deslizante" },
   1605: { name: "Aducción de Copenhague" },
   1640: { name: "Sentadilla Frontal con Mancuernas" },
   1641: { name: "Peso Muerto a una Pierna con Pesa Rusa" },
   1642: { name: "Empuje de Cadera con Mancuernas" },
   1651: { name: "Zancada hacia Atrás con Mancuernas" },
   1652: { name: "Peso Muerto Rumano con Mancuernas" },
   1653: { name: "Sentadilla Lateral con Mancuernas" },
   1684: { name: "Thruster con Mancuernas" },
   1688: { name: "Peso Muerto Rumano con Apoyo" },
   1706: { name: "Sentadilla Búlgara con Mancuernas" },
   1723: { name: "Patada de Glúteos (Máquina)" },
   1724: { name: "Aducción de Pie (Polea)" },
   1735: { name: "Glúteo en Prensa a una Pierna" },
   1739: { name: "Sentadilla Camarón" },
   1740: { name: "Puente de Glúteos Unilateral" },
   1747: { name: "Sentadillas Smith" },
   1748: { name: "Abducción en Máquina" },
   1801: { name: "Sentadilla Completa con Barra" },
   1803: { name: "Sentadilla con Barra Trampa" },
   1829: { name: "Sentadilla con Press en Landmine" },
   1830: { name: "Zancada hacia Atrás con Barra" },
   1886: { name: "Abducción de Cadera Supino" },
   1903: { name: "Zancadas Caminando" },
   1907: { name: "Zancadas Unilaterales" },
   1913: { name: "Hip Thrust Unilateral" },
   1935: { name: "Sentadilla con Cinturón" },
   1947: { name: "Arrancada con Mancuernas" },
   1948: { name: "Sentadilla a una Pierna en Cajón" },
   1956: { name: "Círculos de Hidrante" },
   1963: { name: "Sentadilla Lenta" },
   1965: { name: "Marcha con Rodillas Altas" },

   // ---- ABDOMEN (wgerCategoryId=10) ----
   145:  { name: "Woodchoppers en Polea" },
   165:  { name: "Abdominales en Balón de Estabilidad" },
   174:  { name: "Crunch con Piernas Elevadas" },
   235:  { name: "Patadas de Aleteo (Flutter Kicks)" },
   283:  { name: "Elevaciones de Piernas Colgado" },
   382:  { name: "L-Sit con Resistencia" },
   439:  { name: "Curl en Polea con Agarre Prono" },
   607:  { name: "Splinter Sit-ups" },
   675:  { name: "Turkish Get-Up (Kettlebell)" },
   958:  { name: "Curl de Bíceps con TRX" },
   959:  { name: "Remo en TRX" },
   960:  { name: "Swing con Pesa Rusa" },
   976:  { name: "V-up con Balón Medicinal" },
   977:  { name: "Sentadilla al Cajón" },
   978:  { name: "Elevaciones de Rodillas Colgado" },
   979:  { name: "Elevaciones de Piernas Colgado" },
   980:  { name: "Dominadas Comando (Typewriter)" },
   1103: { name: "Puente Caminando" },
   1193: { name: "Abdominales Rusas" },
   1238: { name: "Frog Stand" },
   1245: { name: "Frontal Lever" },
   1246: { name: "TRX Roll Out" },
   1248: { name: "Dominada a Palanca (Ice Cream Maker)" },
   1252: { name: "Frontal Lever Jalón-up" },
   1259: { name: "Oblicuos en TRX" },
   1286: { name: "Dynamic Planche" },
   1287: { name: "Reach Ups" },
   1288: { name: "Planche Lateral Dinámica" },
   1292: { name: "Dominadas con Agarre Inverso" },
   1293: { name: "Press Ups a un Brazo" },
   1307: { name: "Plancha Frontal" },
   1319: { name: "Abdominales HD" },
   1322: { name: "Kopfüber (Levantamiento de Peso)" },
   1374: { name: "Rotación de Torso en Máquina" },
   1377: { name: "Torso Twist" },
   1406: { name: "Plancha con Extensión de Codo" },
   1415: { name: "Abdominales con Mancuerna" },
   1425: { name: "Toques de Pie Alternados" },
   1426: { name: "Crunch Lateral de Pie" },
   1474: { name: "Elevación en W" },
   1475: { name: "Black Widow Knee Slides" },
   1476: { name: "Butterfly Sit Up" },
   1477: { name: "Sentado Corkscrew" },
   1478: { name: "Levitation Crunch" },
   1479: { name: "Sit Up con Empuje de Codo" },
   1489: { name: "Plancha Jacks" },
   1529: { name: "Toes to Bar" },
   1572: { name: "Bird Dog" },
   1573: { name: "Ab Wheel" },
   1590: { name: "Estiramiento de Brazos y Cuello" },
   1648: { name: "Weighted Crunch" },
   1650: { name: "Side Bend con Mancuernas" },
   1743: { name: "Windshield Wipers" },
   1766: { name: "Plancha Reach" },
   1772: { name: "Reverse Crunch" },
   1776: { name: "Suitcase Carry" },
   1779: { name: "Landmine Rotación" },
   1810: { name: "Sphinx" },
   1823: { name: "Clamshell" },
   1847: { name: "Straddle L-Sit" },
   1852: { name: "L-Sit" },
   1853: { name: "L-Sit (Pies Apoyados)" },
   1889: { name: "Elevación de Piernas en Banco Declinado" },
   1909: { name: "Ab Wheel de Piernas" },
   1912: { name: "Rotación de Core" },
   1924: { name: "3008 Abdominal Crunch" },
   1933: { name: "Abdominal Crunch" },
   1966: { name: "Rotación Torácica en Cuadrupedia" },

   // ---- PANTORRILLAS (wgerCategoryId=14) ----
   146:  { name: "Elevación de Gemelos en Prensa" },
   1200: { name: "Elevación de Tibial Anterior" },
   1620: { name: "Elevación de Pantorrilla Sentado con Mancuerna" },

   // ---- PECHO (wgerCategoryId=11) ----
   75:   { name: "Press de Banca con Mancuernas" },
   308:  { name: "Aperturas Inclinadas con Mancuernas" },
   313:  { name: "Flexiones Inclinadas" },
   314:  { name: "Wipers Isométricos" },
   379:  { name: "Press de Pecho en Máquina" },
   386:  { name: "Flexiones Diamante" },
   445:  { name: "Press de Banca con Pausa" },
   537:  { name: "Press Inclinado en Banco con Mancuernas" },
   538:  { name: "Press de Banca Inclinado" },
   583:  { name: "Flexiones de lado a lado" },
   1084: { name: "Press en Suelo con Mancuernas" },
   1086: { name: "Flexiones con Agarre Cerrado" },
   1111: { name: "Flexiones Inclinadas" },
   1112: { name: "Flexiones Declinadas" },
   1113: { name: "Flexiones en paralelas" },
   1277: { name: "Press Inclinado con Mancuernas" },
   1353: { name: "Hex Press con Mancuernas" },
   1436: { name: "Press en Banco con Barra desde Pines" },
   1496: { name: "Variación de Pecho Superior con Mancuernas" },
   1551: { name: "Flexiones" },
   1554: { name: "Flexiones con Palmada" },
   1583: { name: "Press de Banca Supino" },
   1656: { name: "Press de Pecho Declinado en Polea" },
   1660: { name: "Press de Pecho Inclinado en Polea" },
   1689: { name: "Aperturas en Polea para Pecho Medio" },
   1692: { name: "Press Inclinado en Smith" },
   1693: { name: "Resistencia Estática Inclinada" },
   1694: { name: "Press en Máquina Plano" },
   1773: { name: "Press Inclinado en Banco Legend" },
   1777: { name: "Flexiones con Déficit" },
   1883: { name: "Press de Pecho en Máquina" },
   1902: { name: "Flexiones con Peso" },

   // ---- PANTORRILLAS (wgerCategoryId=14) ----
   590:  { name: "Elevación de Talón Sentado" },
    622:  { name: "Elevación de Talón de Pie" },
    702:  { name: "Elevación de Pantorrilla Izquierda" },
    1021: { name: "Elevación de Pantorrilla Derecha" },
    1203: { name: "Elevación de Pantorrilla Pierna Izquierda" },
    1603: { name: "Curl de Piernas con Banda Elástica" },
    1876: { name: "Estiramiento de Pantorrilla Asistido" },
   1915: { name: "Abducción de Cadera en Cuadrupedia", category_id: 9 },

   // ---- ABDOMEN (wgerCategoryId=10) ----
   9:    { name: "Swing con Pesa Rusa a Dos Manos" },
   260:  { name: "Patada lateral por debajo (Cuatro patas)" },
   297:  { name: "Hollow Position (Barquito)" },
   312:  { name: "Plancha Inclinada con Toque de Suelo" },
   377:  { name: "Elevación de Piernas Acostado" },
   378:  { name: "Elevación de Piernas de Pie" },
   427:  { name: "Encogimientos Negativos" },
   500:  { name: "Plancha Reversa" },
   505:  { name: "Crunch en Silla Romana" },
   545:  { name: "Patadas de tijera" },
   556:  { name: "Flexiones Laterales en Máquina" },
   576:  { name: "Crunch Lateral" },
   577:  { name: "Flexión Lateral con Mancuernas" },
   672:  { name: "Rotación de Tronco en Polea" },
   1089: { name: "Abdominales Rusos" },
   1090: { name: "V-Push Up" },
   1099: { name: "Resistencia Lateral Dinámica" },
    1101: { name: "Isometría de Tracción Horizontal" },
    1194: { name: "Press Pallof" },

    // ---- PIERNAS (wgerCategoryId=9) ----
   294:  { name: "Empuje de Cadera con Barra" },
   320:  { name: "Policheles" },
   331:  { name: "Péndulo con pesa rusa" },
   364:  { name: "Curl Femoral" },
   365:  { name: "Curl Femoral Acostado" },
   366:  { name: "Curl Femoral Sentado" },
   367:  { name: "Curl Femoral de Pie" },
   369:  { name: "Curl de Cuádriceps" },
   373:  { name: "Prensa de Piernas Cerrada" },
   374:  { name: "Prensa de Piernas Abierta" },
   375:  { name: "Sentadilla Hack en Máquina" },
   376:  { name: "Elevación de Piernas" },
   397:  { name: "Sentadilla Ancha en Cajón" },
   441:  { name: "Sentadilla Overhead" },
   456:  { name: "Sentadilla a una pierna" },
   507:  { name: "Peso Muerto Rumano con Barra" },
   604:  { name: "Peso Muerto de Velocidad" },
};

async function main() {
  const ids = Object.keys(FIXES).map(Number);
  const { data: exercises, error } = await supabase
    .from("exercises")
    .select("id, name, category_id")
    .in("id", ids);

  if (error || !exercises) {
    console.error("Error fetching:", error?.message);
    process.exit(1);
  }

  console.log(`Found ${exercises.length} of ${ids.length} exercises\n`);

  for (const ex of exercises) {
    const fix = FIXES[ex.id];
    if (!fix) continue;

    const update: Record<string, unknown> = { name: fix.name, updated_at: new Date().toISOString() };
    if (fix.category_id !== undefined) {
      update.category_id = fix.category_id;
    }

    const { error: updateError } = await supabase
      .from("exercises")
      .update(update)
      .eq("id", ex.id);

    if (updateError) {
      console.error(`  [ERR] ID=${ex.id}: ${updateError.message}`);
    } else {
      const extra = fix.category_id !== undefined ? " (movido a Antebrazos)" : "";
      console.log(`  ID=${ex.id}: "${ex.name}" → "${fix.name}"${extra}`);
    }
  }

  console.log("\nDone");
}

main().catch(console.error);
